### PR TITLE
Bugfix ctruth table

### PR DESCRIPTION
**Pull request by kasimebrahim**
per issue https://github.com/singnet/as-moses/issues/67

### CODE REVIEW

**Comment by ngeiswei** [comment]
Thanks @kasimebrahim, your fix looks correct, however `ASMOSESUTest` is failing now, any idea why?

**Comment by kasimebrahim** [comment]
It is failing because the converter doesn't support id::exp -Hsr is a regression problem right? what I still dont get is why now it should have failed long ago.

**Comment by ngeiswei** [comment]
Oh, I think I know why, your fix takes care of all constants, and so I suspect constants in `test_atomese_sr_3` were wrongly maximizing the score, preventing the run from building candidates with operators such as `id::exp`.

**Comment by ngeiswei** [comment]
I'm gonna merge and we can fix that test in another PR. In any case that unit test should be completed.

**Comment by kasimebrahim** [comment]
Before the above commits The interpreter used to return an empty floatvalue for constant programs such as NumberNode0 and the behavioural score used to be an empty vector. That used to lead to termination criteria and it never encountered a program like id::exp. Now that the interpreter returns the right values[or at least different one] it get a chance to evolve to id::exp and the converter dosent support it.

I added this in the instancescorer before to_atomese is called to see what is going on
<pre>
	for (vertex v : tr) {
		if (boost::get<builtin>(&v) == id::exp) {
                        < log >
			return composite_score();
		}
	}
</pre>
before the above commits < log > never reached.

**Pull request merged**
