### PR TITLE
Rename asmoses/moses to asmoses/opencog

### PR DESCRIPTION
**Pull request by Bitseat**
Change path from moses/moses to opencog/moses

Fixed CythonMoses test failure

### CODE REVIEW

**Comment by ngeiswei** [comment]
That looks good @Bitseat , you probably just need to rebase onto to master to resolve the conflicts.

**Comment by ngeiswei** [comment]
@Bitseat one last thing, you need fix the WIN32 else branches as well, such as https://github.com/singnet/as-moses/blob/master/moses/combo/CMakeLists.txt#L69-L74

**Comment by ngeiswei** [comment]
For those who wonder, MOSES does actually compile under Windows (at least it did last time we tried, few years ago). Maybe we could remove the WIN32 branches, I mean, just like I said 15 years ago, it's clear Windows is gonna tank any moment now... Or is it?

**Comment by Bitseat** [comment]
@ngeiswei  All done. I hope it's ready.

**Comment by ngeiswei** [comment]
@Bitseat actually there are more `CMakeLists.txt` files to correct, here's the list

```
data/CMakeLists.txt
moses/CMakeLists.txt
moses/main/CMakeLists.txt
reduct/CMakeLists.txt
feature-selection/CMakeLists.txt
atomese/CMakeLists.txt
```

That way we'll have all as-moses libraries under `usr/local/lib/opencog`.

Thanks.

**Comment by Bitseat** [comment]
@ngeiswei my bad. Can you please check it again.

**Comment by ngeiswei** [comment]
It looks good thanks!

**Pull request merged**
